{
 "title": "Traefik",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job:", "query": "label_values(job)" },
   {
    "name": "protocol",
    "label": "Service:",
    "query": "label_values(traefik_service_requests_total, protocol)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Traefik Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(traefik_service_open_connections)"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": " latency Over 5 min 95th Percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traefik_entrypoint_request_duration_seconds_bucket{code=\"200\",method=\"GET\"}[5m])) by (le))",
     "legendFormat": "{{ $job }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Status code 200 average over the last 5min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{code=\"200\"}[5m])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes over 30m",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(traefik_entrypoint_requests_total{}[30m]) * 100",
     "legendFormat": "{{ method }} : {{code}}"
    },
    { "expr": "avg_over_time" }
   ]
  },
  {
   "title": "Total Requests Since Starting",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "traefik_service_requests_total", "legendFormat": "{{code}} | {{method}}" }
   ]
  },
  {
   "title": "Used sockets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "SERVICE - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}